# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

andEq <- function(x, y) {
    .Call('_filterr_andEq', PACKAGE = 'filterr', x, y)
}

orEq <- function(x, y) {
    .Call('_filterr_orEq', PACKAGE = 'filterr', x, y)
}

